trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '14.x'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build the project'

- script: npm test
  displayName: 'Run tests'

- script: |
    echo "Build completed on $(date)"
  displayName: 'Post-build step'
